<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AuthorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $authors = [
            [
                'name' => 'Maria Santos',
                'biography' => 'Educational specialist with over 15 years of experience in Pacific Island education. Focused on culturally responsive pedagogy.',
                'birth_year' => 1975,
                'death_year' => null,
                'nationality' => 'Micronesian',
                'website' => 'https://example.com/maria-santos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. James Refaluwasch',
                'biography' => 'Professor of Pacific Studies and native Carolinian speaker. Specialist in indigenous language preservation.',
                'birth_year' => 1968,
                'death_year' => null,
                'nationality' => 'Carolinian',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anna Nakamura',
                'biography' => 'Mathematics educator and curriculum developer for elementary education in Micronesia.',
                'birth_year' => 1982,
                'death_year' => null,
                'nationality' => 'Japanese-American',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elder Joseph Urusemal',
                'biography' => 'Traditional storyteller and cultural keeper from Chuuk. Dedicated to preserving oral traditions.',
                'birth_year' => 1943,
                'death_year' => null,
                'nationality' => 'Chuukese',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Sarah Williams',
                'biography' => 'Marine biologist and environmental education specialist. Expert in Pacific coral reef ecosystems.',
                'birth_year' => 1971,
                'death_year' => null,
                'nationality' => 'American',
                'website' => 'https://example.com/sarah-williams',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peter Segal',
                'biography' => 'Historical researcher specializing in Micronesian history and World War II Pacific theater.',
                'birth_year' => 1965,
                'death_year' => null,
                'nationality' => 'Australian',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rosa Mendiola',
                'biography' => 'Chamorro language teacher and children\'s book author. Advocate for bilingual education.',
                'birth_year' => 1978,
                'death_year' => null,
                'nationality' => 'Chamorro',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Michael Chen',
                'biography' => 'Physics professor and science education researcher. Develops hands-on learning materials.',
                'birth_year' => 1969,
                'death_year' => null,
                'nationality' => 'Chinese-American',
                'website' => 'https://example.com/michael-chen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leilani Kihleng',
                'biography' => 'Pohnpeian poet and cultural educator. Works to preserve and promote Pohnpeian language.',
                'birth_year' => 1984,
                'death_year' => null,
                'nationality' => 'Pohnpeian',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Robert Pacific Education Collective',
                'biography' => 'Collaborative group of educators from across Micronesia working on curriculum development.',
                'birth_year' => null,
                'death_year' => null,
                'nationality' => 'Multinational',
                'website' => 'https://example.com/pacific-education',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Elizabeth Hadley',
                'biography' => 'Reading specialist and literacy coach. Expert in multilingual literacy development.',
                'birth_year' => 1973,
                'death_year' => null,
                'nationality' => 'American',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Francis Toribiong',
                'biography' => 'Palauan educator and traditional navigation expert. Teaches traditional Palauan practices.',
                'birth_year' => 1959,
                'death_year' => null,
                'nationality' => 'Palauan',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Jennifer Kumar',
                'biography' => 'Social studies curriculum specialist with focus on Pacific Island civics education.',
                'birth_year' => 1976,
                'death_year' => null,
                'nationality' => 'Indian-American',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thomas Remengesau',
                'biography' => 'Palauan statesman and environmental advocate. Authored materials on governance and conservation.',
                'birth_year' => 1956,
                'death_year' => null,
                'nationality' => 'Palauan',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Amanda Foster',
                'biography' => 'Chemistry educator specializing in hands-on laboratory experiences for island schools.',
                'birth_year' => 1980,
                'death_year' => null,
                'nationality' => 'Canadian',
                'website' => 'https://example.com/amanda-foster',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carmen Bigler',
                'biography' => 'Yapese cultural specialist and traditional craft instructor. Preserves traditional knowledge.',
                'birth_year' => 1962,
                'death_year' => null,
                'nationality' => 'Yapese',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. David Martinez',
                'biography' => 'Geography educator and GIS specialist. Creates interactive mapping materials for Pacific education.',
                'birth_year' => 1974,
                'death_year' => null,
                'nationality' => 'Mexican-American',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Margaret Sigrah',
                'biography' => 'Kosraean language teacher and curriculum developer. Advocates for native language education.',
                'birth_year' => 1966,
                'death_year' => null,
                'nationality' => 'Kosraean',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Kevin O\'Brien',
                'biography' => 'Environmental science educator and climate change researcher focusing on Pacific islands.',
                'birth_year' => 1967,
                'death_year' => null,
                'nationality' => 'Irish-American',
                'website' => 'https://example.com/kevin-obrien',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Linda Capelle',
                'biography' => 'Marshallese educator and traditional knowledge keeper. Specializes in navigation and seafaring.',
                'birth_year' => 1971,
                'death_year' => null,
                'nationality' => 'Marshallese',
                'website' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('authors')->insert($authors);
    }
}
