<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            // Mathematics Books
            [
                'title' => 'Pacific Islands Mathematics: Grade 3',
                'subtitle' => 'Numbers, Shapes, and Problem Solving',
                'isbn' => '978-0-123456-78-9',
                'isbn13' => '978-0123456789',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 1, // Pacific Islands Mathematics Series
                'publication_year' => 2019,
                'edition' => '2nd Edition',
                'pages' => 156,
                'description' => 'A culturally responsive mathematics textbook for third-grade students featuring problems set in Pacific Island contexts.',
                'cover_image' => 'covers/math_grade3.jpg',
                'pdf_file' => 'books/math_grade3.pdf',
                'file_size' => 12345678,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 245,
                'download_count' => 89,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Geometry Through Island Navigation',
                'subtitle' => 'Traditional Wayfinding and Mathematical Concepts',
                'isbn' => '978-0-234567-89-0',
                'isbn13' => '978-0234567890',
                'language_id' => 1, // English
                'publisher_id' => 2, // Micronesian Educational Resources
                'collection_id' => 1, // Pacific Islands Mathematics Series
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 98,
                'description' => 'Explores geometric concepts through the lens of traditional Micronesian navigation techniques.',
                'cover_image' => 'covers/geometry_navigation.jpg',
                'pdf_file' => 'books/geometry_navigation.pdf',
                'file_size' => 8765432,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 156,
                'download_count' => 67,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Chuukese Arithmetic Workbook',
                'subtitle' => 'Pekin aiseach me chon sapw',
                'isbn' => '978-0-345678-90-1',
                'isbn13' => '978-0345678901',
                'language_id' => 2, // Chuukese
                'publisher_id' => 6, // Traditional Knowledge Press
                'collection_id' => 4, // Language Preservation Library
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 72,
                'description' => 'Arithmetic practice book written in Chuukese language for elementary students.',
                'cover_image' => 'covers/chuukese_arithmetic.jpg',
                'pdf_file' => 'books/chuukese_arithmetic.pdf',
                'file_size' => 5432109,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 98,
                'download_count' => 45,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Science Books
            [
                'title' => 'Coral Reef Ecosystems',
                'subtitle' => 'A Guide for Pacific Island Students',
                'isbn' => '978-0-456789-01-2',
                'isbn13' => '978-0456789012',
                'language_id' => 1, // English
                'publisher_id' => 8, // Oceanic Educational Materials
                'collection_id' => 6, // Marine Environment Studies
                'publication_year' => 2018,
                'edition' => '3rd Edition',
                'pages' => 234,
                'description' => 'Comprehensive study of coral reef ecosystems with focus on Pacific marine biodiversity.',
                'cover_image' => 'covers/coral_reefs.jpg',
                'pdf_file' => 'books/coral_reefs.pdf',
                'file_size' => 15678901,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 387,
                'download_count' => 156,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Climate Change in the Pacific',
                'subtitle' => 'Understanding Environmental Impacts',
                'isbn' => '978-0-567890-12-3',
                'isbn13' => '978-0567890123',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 2, // Micronesian Science Fundamentals
                'publication_year' => 2022,
                'edition' => '1st Edition',
                'pages' => 189,
                'description' => 'Educational resource on climate change effects specifically affecting Pacific island nations.',
                'cover_image' => 'covers/climate_change.jpg',
                'pdf_file' => 'books/climate_change.pdf',
                'file_size' => 13456789,
                'access_level' => 'limited',
                'is_featured' => false,
                'view_count' => 267,
                'download_count' => 78,
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Language Arts Books
            [
                'title' => 'Stories from the Deep',
                'subtitle' => 'Traditional Micronesian Folktales',
                'isbn' => '978-0-678901-23-4',
                'isbn13' => '978-0678901234',
                'language_id' => 1, // English
                'publisher_id' => 4, // Cultural Heritage Books
                'collection_id' => 3, // Traditional Stories Collection
                'publication_year' => 2017,
                'edition' => '2nd Edition',
                'pages' => 145,
                'description' => 'Collection of traditional stories from various Micronesian cultures, retold for modern readers.',
                'cover_image' => 'covers/stories_deep.jpg',
                'pdf_file' => 'books/stories_deep.pdf',
                'file_size' => 9876543,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 445,
                'download_count' => 234,
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pohnpeian Reading Primer',
                'subtitle' => 'Tehn padahk en Pohnpei',
                'isbn' => '978-0-789012-34-5',
                'isbn13' => '978-0789012345',
                'language_id' => 3, // Pohnpeian
                'publisher_id' => 2, // Micronesian Educational Resources
                'collection_id' => 8, // Primary Reading Adventures
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 68,
                'description' => 'Beginning reading book in Pohnpeian language for elementary students.',
                'cover_image' => 'covers/pohnpeian_primer.jpg',
                'pdf_file' => 'books/pohnpeian_primer.pdf',
                'file_size' => 4567890,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 123,
                'download_count' => 56,
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Social Studies Books
            [
                'title' => 'History of the Federated States of Micronesia',
                'subtitle' => 'From Ancient Times to Independence',
                'isbn' => '978-0-890123-45-6',
                'isbn13' => '978-0890123456',
                'language_id' => 1, // English
                'publisher_id' => 9, // FSM Department of Education
                'collection_id' => 5, // Pacific History Chronicles
                'publication_year' => 2019,
                'edition' => '4th Edition',
                'pages' => 298,
                'description' => 'Comprehensive history of the Federated States of Micronesia from pre-colonial times to present.',
                'cover_image' => 'covers/fsm_history.jpg',
                'pdf_file' => 'books/fsm_history.pdf',
                'file_size' => 18901234,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 567,
                'download_count' => 289,
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Geography of the Pacific Islands',
                'subtitle' => 'Physical and Human Geography',
                'isbn' => '978-0-901234-56-7',
                'isbn13' => '978-0901234567',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 9, // Island Geography Explorer
                'publication_year' => 2021,
                'edition' => '2nd Edition',
                'pages' => 178,
                'description' => 'Study of Pacific Island geography including physical features, climate, and human settlements.',
                'cover_image' => 'covers/pacific_geography.jpg',
                'pdf_file' => 'books/pacific_geography.pdf',
                'file_size' => 12678901,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 234,
                'download_count' => 112,
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Cultural Studies Books
            [
                'title' => 'Traditional Navigation Techniques',
                'subtitle' => 'Wayfinding Across the Pacific',
                'isbn' => '978-1-012345-67-8',
                'isbn13' => '978-1012345678',
                'language_id' => 1, // English
                'publisher_id' => 4, // Cultural Heritage Books
                'collection_id' => 7, // Cultural Practices Manual
                'publication_year' => 2018,
                'edition' => '1st Edition',
                'pages' => 156,
                'description' => 'Guide to traditional Pacific navigation methods and their cultural significance.',
                'cover_image' => 'covers/navigation.jpg',
                'pdf_file' => 'books/navigation.pdf',
                'file_size' => 11234567,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 345,
                'download_count' => 167,
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Additional books to reach 50 total
            [
                'title' => 'Yapese Stone Money',
                'subtitle' => 'Traditional Economics and Culture',
                'isbn' => '978-1-123456-78-9',
                'isbn13' => '978-1123456789',
                'language_id' => 4, // Yapese
                'publisher_id' => 6, // Traditional Knowledge Press
                'collection_id' => 7, // Cultural Practices Manual
                'publication_year' => 2019,
                'edition' => '1st Edition',
                'pages' => 89,
                'description' => 'Study of traditional Yapese stone money system and its cultural significance.',
                'cover_image' => 'covers/stone_money.jpg',
                'pdf_file' => 'books/stone_money.pdf',
                'file_size' => 6789012,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 178,
                'download_count' => 89,
                'sort_order' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kosraean Language Dictionary',
                'subtitle' => 'English-Kosraean / Kosraean-English',
                'isbn' => '978-1-234567-89-0',
                'isbn13' => '978-1234567890',
                'language_id' => 5, // Kosraean
                'publisher_id' => 2, // Micronesian Educational Resources
                'collection_id' => 4, // Language Preservation Library
                'publication_year' => 2020,
                'edition' => '3rd Edition',
                'pages' => 345,
                'description' => 'Comprehensive dictionary for Kosraean language learners and speakers.',
                'cover_image' => 'covers/kosraean_dict.jpg',
                'pdf_file' => 'books/kosraean_dict.pdf',
                'file_size' => 23456789,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 456,
                'download_count' => 234,
                'sort_order' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Marine Biology of Micronesia',
                'subtitle' => 'Fish, Corals, and Marine Life',
                'isbn' => '978-1-345678-90-1',
                'isbn13' => '978-1345678901',
                'language_id' => 1, // English
                'publisher_id' => 7, // University of Guam Press
                'collection_id' => 6, // Marine Environment Studies
                'publication_year' => 2021,
                'edition' => '2nd Edition',
                'pages' => 267,
                'description' => 'Detailed study of marine species found in Micronesian waters.',
                'cover_image' => 'covers/marine_biology.jpg',
                'pdf_file' => 'books/marine_biology.pdf',
                'file_size' => 16789012,
                'access_level' => 'limited',
                'is_featured' => false,
                'view_count' => 289,
                'download_count' => 134,
                'sort_order' => 13,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Elementary Physics',
                'subtitle' => 'Forces, Energy, and Motion',
                'isbn' => '978-1-456789-01-2',
                'isbn13' => '978-1456789012',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 2, // Micronesian Science Fundamentals
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 145,
                'description' => 'Introduction to physics concepts for middle school students.',
                'cover_image' => 'covers/elem_physics.jpg',
                'pdf_file' => 'books/elem_physics.pdf',
                'file_size' => 10123456,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 167,
                'download_count' => 78,
                'sort_order' => 14,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Marshallese Legends and Stories',
                'subtitle' => 'Tales from the Marshall Islands',
                'isbn' => '978-1-567890-12-3',
                'isbn13' => '978-1567890123',
                'language_id' => 6, // Marshallese
                'publisher_id' => 3, // Island Academic Publishing
                'collection_id' => 3, // Traditional Stories Collection
                'publication_year' => 2018,
                'edition' => '1st Edition',
                'pages' => 123,
                'description' => 'Collection of traditional Marshallese stories and legends.',
                'cover_image' => 'covers/marshallese_stories.jpg',
                'pdf_file' => 'books/marshallese_stories.pdf',
                'file_size' => 8901234,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 234,
                'download_count' => 145,
                'sort_order' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Basic Chemistry for Islands',
                'subtitle' => 'Understanding Chemical Processes',
                'isbn' => '978-1-678901-23-4',
                'isbn13' => '978-1678901234',
                'language_id' => 1, // English
                'publisher_id' => 8, // Oceanic Educational Materials
                'collection_id' => 2, // Micronesian Science Fundamentals
                'publication_year' => 2019,
                'edition' => '1st Edition',
                'pages' => 198,
                'description' => 'Introduction to chemistry with practical applications for island environments.',
                'cover_image' => 'covers/basic_chemistry.jpg',
                'pdf_file' => 'books/basic_chemistry.pdf',
                'file_size' => 14567890,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 145,
                'download_count' => 67,
                'sort_order' => 16,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Palauan Cultural Practices',
                'subtitle' => 'Traditions and Customs',
                'isbn' => '978-1-789012-34-5',
                'isbn13' => '978-1789012345',
                'language_id' => 7, // Palauan
                'publisher_id' => 4, // Cultural Heritage Books
                'collection_id' => 7, // Cultural Practices Manual
                'publication_year' => 2017,
                'edition' => '2nd Edition',
                'pages' => 167,
                'description' => 'Guide to traditional Palauan cultural practices and ceremonies.',
                'cover_image' => 'covers/palauan_culture.jpg',
                'pdf_file' => 'books/palauan_culture.pdf',
                'file_size' => 12345678,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 189,
                'download_count' => 89,
                'sort_order' => 17,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Economics',
                'subtitle' => 'Trade and Commerce in Island Nations',
                'isbn' => '978-1-890123-45-6',
                'isbn13' => '978-1890123456',
                'language_id' => 1, // English
                'publisher_id' => 10, // Pacific Scholars Collective
                'collection_id' => null,
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 234,
                'description' => 'Study of economic systems and trade relationships in Pacific island nations.',
                'cover_image' => 'covers/pacific_economics.jpg',
                'pdf_file' => 'books/pacific_economics.pdf',
                'file_size' => 15678901,
                'access_level' => 'limited',
                'is_featured' => false,
                'view_count' => 123,
                'download_count' => 45,
                'sort_order' => 18,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Carolinian Language Basics',
                'subtitle' => 'Refaluwasch Language Learning',
                'isbn' => '978-1-901234-56-7',
                'isbn13' => '978-1901234567',
                'language_id' => 8, // Carolinian
                'publisher_id' => 5, // CNMI Educational Foundation
                'collection_id' => 4, // Language Preservation Library
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 89,
                'description' => 'Beginning language course for learning Carolinian (Refaluwasch).',
                'cover_image' => 'covers/carolinian_basics.jpg',
                'pdf_file' => 'books/carolinian_basics.pdf',
                'file_size' => 6789012,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 98,
                'download_count' => 34,
                'sort_order' => 19,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'World War II in the Pacific',
                'subtitle' => 'Impact on Micronesian Islands',
                'isbn' => '978-2-012345-67-8',
                'isbn13' => '978-2012345678',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 5, // Pacific History Chronicles
                'publication_year' => 2019,
                'edition' => '3rd Edition',
                'pages' => 278,
                'description' => 'Historical account of World War II and its effects on Micronesian communities.',
                'cover_image' => 'covers/wwii_pacific.jpg',
                'pdf_file' => 'books/wwii_pacific.pdf',
                'file_size' => 17890123,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 456,
                'download_count' => 234,
                'sort_order' => 20,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Chamorro Legends and Folklore',
                'subtitle' => 'Stories from Guam and Saipan',
                'isbn' => '978-2-123456-78-9',
                'isbn13' => '978-2123456789',
                'language_id' => 9, // Chamorro
                'publisher_id' => 7, // University of Guam Press
                'collection_id' => 3, // Traditional Stories Collection
                'publication_year' => 2018,
                'edition' => '2nd Edition',
                'pages' => 134,
                'description' => 'Collection of traditional Chamorro stories and legends.',
                'cover_image' => 'covers/chamorro_folklore.jpg',
                'pdf_file' => 'books/chamorro_folklore.pdf',
                'file_size' => 9012345,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 178,
                'download_count' => 89,
                'sort_order' => 21,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Environmental Conservation',
                'subtitle' => 'Protecting Pacific Island Ecosystems',
                'isbn' => '978-2-234567-89-0',
                'isbn13' => '978-2234567890',
                'language_id' => 1, // English
                'publisher_id' => 8, // Oceanic Educational Materials
                'collection_id' => 6, // Marine Environment Studies
                'publication_year' => 2022,
                'edition' => '1st Edition',
                'pages' => 189,
                'description' => 'Guide to environmental conservation practices for Pacific islands.',
                'cover_image' => 'covers/conservation.jpg',
                'pdf_file' => 'books/conservation.pdf',
                'file_size' => 13456789,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 289,
                'download_count' => 156,
                'sort_order' => 22,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Statistics for Island Communities',
                'subtitle' => 'Data Analysis and Interpretation',
                'isbn' => '978-2-345678-90-1',
                'isbn13' => '978-2345678901',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 1, // Pacific Islands Mathematics Series
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 167,
                'description' => 'Introduction to statistics with applications relevant to Pacific island communities.',
                'cover_image' => 'covers/statistics.jpg',
                'pdf_file' => 'books/statistics.pdf',
                'file_size' => 11567890,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 145,
                'download_count' => 67,
                'sort_order' => 23,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Traditional Fishing Methods',
                'subtitle' => 'Sustainable Practices of the Pacific',
                'isbn' => '978-2-456789-01-2',
                'isbn13' => '978-2456789012',
                'language_id' => 1, // English
                'publisher_id' => 6, // Traditional Knowledge Press
                'collection_id' => 7, // Cultural Practices Manual
                'publication_year' => 2019,
                'edition' => '1st Edition',
                'pages' => 145,
                'description' => 'Guide to traditional and sustainable fishing practices in the Pacific.',
                'cover_image' => 'covers/fishing_methods.jpg',
                'pdf_file' => 'books/fishing_methods.pdf',
                'file_size' => 10234567,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 167,
                'download_count' => 78,
                'sort_order' => 24,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Government and Civics',
                'subtitle' => 'Understanding Pacific Island Democracy',
                'isbn' => '978-2-567890-12-3',
                'isbn13' => '978-2567890123',
                'language_id' => 1, // English
                'publisher_id' => 9, // FSM Department of Education
                'collection_id' => null,
                'publication_year' => 2020,
                'edition' => '2nd Edition',
                'pages' => 198,
                'description' => 'Study of government systems and civic responsibilities in Pacific nations.',
                'cover_image' => 'covers/civics.jpg',
                'pdf_file' => 'books/civics.pdf',
                'file_size' => 14123456,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 234,
                'download_count' => 123,
                'sort_order' => 25,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Art and Crafts',
                'subtitle' => 'Traditional and Contemporary Works',
                'isbn' => '978-2-678901-23-4',
                'isbn13' => '978-2678901234',
                'language_id' => 1, // English
                'publisher_id' => 4, // Cultural Heritage Books
                'collection_id' => 7, // Cultural Practices Manual
                'publication_year' => 2018,
                'edition' => '1st Edition',
                'pages' => 156,
                'description' => 'Exploration of traditional and contemporary Pacific island art forms.',
                'cover_image' => 'covers/art_crafts.jpg',
                'pdf_file' => 'books/art_crafts.pdf',
                'file_size' => 12789012,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 189,
                'download_count' => 89,
                'sort_order' => 26,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ulithian Language Guide',
                'subtitle' => 'Woleaian Language Learning',
                'isbn' => '978-2-789012-34-5',
                'isbn13' => '978-2789012345',
                'language_id' => 10, // Ulithian
                'publisher_id' => 2, // Micronesian Educational Resources
                'collection_id' => 4, // Language Preservation Library
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 78,
                'description' => 'Language learning guide for Ulithian (Woleaian) speakers.',
                'cover_image' => 'covers/ulithian_guide.jpg',
                'pdf_file' => 'books/ulithian_guide.pdf',
                'file_size' => 5678901,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 67,
                'download_count' => 23,
                'sort_order' => 27,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Algebra for Pacific Students',
                'subtitle' => 'Problem Solving with Cultural Context',
                'isbn' => '978-2-890123-45-6',
                'isbn13' => '978-2890123456',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 1, // Pacific Islands Mathematics Series
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 234,
                'description' => 'Algebra textbook with problems set in Pacific island contexts.',
                'cover_image' => 'covers/algebra.jpg',
                'pdf_file' => 'books/algebra.pdf',
                'file_size' => 16234567,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 178,
                'download_count' => 89,
                'sort_order' => 28,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Reading Comprehension Strategies',
                'subtitle' => 'Building Literacy Skills',
                'isbn' => '978-2-901234-56-7',
                'isbn13' => '978-2901234567',
                'language_id' => 1, // English
                'publisher_id' => 10, // Pacific Scholars Collective
                'collection_id' => 8, // Primary Reading Adventures
                'publication_year' => 2019,
                'edition' => '2nd Edition',
                'pages' => 145,
                'description' => 'Strategies and exercises for improving reading comprehension skills.',
                'cover_image' => 'covers/reading_comp.jpg',
                'pdf_file' => 'books/reading_comp.pdf',
                'file_size' => 10345678,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 234,
                'download_count' => 134,
                'sort_order' => 29,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Island Geology',
                'subtitle' => 'Formation and Structure of Islands',
                'isbn' => '978-3-012345-67-8',
                'isbn13' => '978-3012345678',
                'language_id' => 1, // English
                'publisher_id' => 7, // University of Guam Press
                'collection_id' => 2, // Micronesian Science Fundamentals
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 189,
                'description' => 'Study of geological processes that formed Pacific islands.',
                'cover_image' => 'covers/geology.jpg',
                'pdf_file' => 'books/geology.pdf',
                'file_size' => 13789012,
                'access_level' => 'limited',
                'is_featured' => false,
                'view_count' => 156,
                'download_count' => 67,
                'sort_order' => 30,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Teacher\'s Guide to Pacific Education',
                'subtitle' => 'Culturally Responsive Teaching Methods',
                'isbn' => '978-3-123456-78-9',
                'isbn13' => '978-3123456789',
                'language_id' => 1, // English
                'publisher_id' => 10, // Pacific Scholars Collective
                'collection_id' => 10, // Teacher Resource Toolkit
                'publication_year' => 2022,
                'edition' => '1st Edition',
                'pages' => 267,
                'description' => 'Professional development guide for teachers in Pacific island schools.',
                'cover_image' => 'covers/teacher_guide.jpg',
                'pdf_file' => 'books/teacher_guide.pdf',
                'file_size' => 18456789,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 345,
                'download_count' => 189,
                'sort_order' => 31,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Assessment Strategies',
                'subtitle' => 'Evaluating Student Learning',
                'isbn' => '978-3-234567-89-0',
                'isbn13' => '978-3234567890',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 10, // Teacher Resource Toolkit
                'publication_year' => 2021,
                'edition' => '2nd Edition',
                'pages' => 178,
                'description' => 'Guide to effective assessment methods for Pacific island classrooms.',
                'cover_image' => 'covers/assessment.jpg',
                'pdf_file' => 'books/assessment.pdf',
                'file_size' => 12567890,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 189,
                'download_count' => 78,
                'sort_order' => 32,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Music and Dance',
                'subtitle' => 'Traditional Performing Arts',
                'isbn' => '978-3-345678-90-1',
                'isbn13' => '978-3345678901',
                'language_id' => 1, // English
                'publisher_id' => 4, // Cultural Heritage Books
                'collection_id' => 7, // Cultural Practices Manual
                'publication_year' => 2019,
                'edition' => '1st Edition',
                'pages' => 145,
                'description' => 'Guide to traditional music and dance forms of the Pacific islands.',
                'cover_image' => 'covers/music_dance.jpg',
                'pdf_file' => 'books/music_dance.pdf',
                'file_size' => 11234567,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 167,
                'download_count' => 89,
                'sort_order' => 33,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Writing Skills Workbook',
                'subtitle' => 'Creative and Academic Writing',
                'isbn' => '978-3-456789-01-2',
                'isbn13' => '978-3456789012',
                'language_id' => 1, // English
                'publisher_id' => 8, // Oceanic Educational Materials
                'collection_id' => 8, // Primary Reading Adventures
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 123,
                'description' => 'Workbook for developing writing skills in elementary and middle school students.',
                'cover_image' => 'covers/writing_skills.jpg',
                'pdf_file' => 'books/writing_skills.pdf',
                'file_size' => 8901234,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 145,
                'download_count' => 67,
                'sort_order' => 34,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Climate Science for Islands',
                'subtitle' => 'Weather, Climate, and Adaptation',
                'isbn' => '978-3-567890-12-3',
                'isbn13' => '978-3567890123',
                'language_id' => 1, // English
                'publisher_id' => 7, // University of Guam Press
                'collection_id' => 2, // Micronesian Science Fundamentals
                'publication_year' => 2022,
                'edition' => '1st Edition',
                'pages' => 198,
                'description' => 'Study of climate science with focus on Pacific island environments.',
                'cover_image' => 'covers/climate_science.jpg',
                'pdf_file' => 'books/climate_science.pdf',
                'file_size' => 14678901,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 234,
                'download_count' => 123,
                'sort_order' => 35,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Literature Anthology',
                'subtitle' => 'Contemporary Voices from the Islands',
                'isbn' => '978-3-678901-23-4',
                'isbn13' => '978-3678901234',
                'language_id' => 1, // English
                'publisher_id' => 10, // Pacific Scholars Collective
                'collection_id' => null,
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 234,
                'description' => 'Collection of contemporary literature from Pacific island authors.',
                'cover_image' => 'covers/literature_anthology.jpg',
                'pdf_file' => 'books/literature_anthology.pdf',
                'file_size' => 16789012,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 189,
                'download_count' => 89,
                'sort_order' => 36,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Health Education for Islands',
                'subtitle' => 'Nutrition, Wellness, and Disease Prevention',
                'isbn' => '978-3-789012-34-5',
                'isbn13' => '978-3789012345',
                'language_id' => 1, // English
                'publisher_id' => 8, // Oceanic Educational Materials
                'collection_id' => null,
                'publication_year' => 2020,
                'edition' => '2nd Edition',
                'pages' => 167,
                'description' => 'Health education resource addressing issues specific to Pacific island communities.',
                'cover_image' => 'covers/health_education.jpg',
                'pdf_file' => 'books/health_education.pdf',
                'file_size' => 12345678,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 156,
                'download_count' => 78,
                'sort_order' => 37,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Island Maps and Geography',
                'subtitle' => 'Interactive Atlas and Activities',
                'isbn' => '978-3-890123-45-6',
                'isbn13' => '978-3890123456',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => 9, // Island Geography Explorer
                'publication_year' => 2019,
                'edition' => '3rd Edition',
                'pages' => 189,
                'description' => 'Interactive atlas with maps and geographic activities for Pacific islands.',
                'cover_image' => 'covers/maps_geography.jpg',
                'pdf_file' => 'books/maps_geography.pdf',
                'file_size' => 15234567,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 234,
                'download_count' => 134,
                'sort_order' => 38,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Vocabulary Building',
                'subtitle' => 'English Language Development',
                'isbn' => '978-3-901234-56-7',
                'isbn13' => '978-3901234567',
                'language_id' => 1, // English
                'publisher_id' => 2, // Micronesian Educational Resources
                'collection_id' => 8, // Primary Reading Adventures
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 134,
                'description' => 'Vocabulary building exercises for English language learners.',
                'cover_image' => 'covers/vocabulary.jpg',
                'pdf_file' => 'books/vocabulary.pdf',
                'file_size' => 9567890,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 178,
                'download_count' => 89,
                'sort_order' => 39,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Astronomy',
                'subtitle' => 'Traditional Navigation and Modern Science',
                'isbn' => '978-4-012345-67-8',
                'isbn13' => '978-4012345678',
                'language_id' => 1, // English
                'publisher_id' => 6, // Traditional Knowledge Press
                'collection_id' => 7, // Cultural Practices Manual
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 145,
                'description' => 'Exploration of traditional Pacific navigation astronomy and modern astronomical science.',
                'cover_image' => 'covers/astronomy.jpg',
                'pdf_file' => 'books/astronomy.pdf',
                'file_size' => 11678901,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 289,
                'download_count' => 156,
                'sort_order' => 40,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Critical Thinking Skills',
                'subtitle' => 'Problem Solving for Pacific Students',
                'isbn' => '978-4-123456-78-9',
                'isbn13' => '978-4123456789',
                'language_id' => 1, // English
                'publisher_id' => 10, // Pacific Scholars Collective
                'collection_id' => 10, // Teacher Resource Toolkit
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 167,
                'description' => 'Development of critical thinking and problem-solving skills.',
                'cover_image' => 'covers/critical_thinking.jpg',
                'pdf_file' => 'books/critical_thinking.pdf',
                'file_size' => 12234567,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 145,
                'download_count' => 67,
                'sort_order' => 41,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sustainable Agriculture',
                'subtitle' => 'Farming Practices for Small Islands',
                'isbn' => '978-4-234567-89-0',
                'isbn13' => '978-4234567890',
                'language_id' => 1, // English
                'publisher_id' => 8, // Oceanic Educational Materials
                'collection_id' => null,
                'publication_year' => 2019,
                'edition' => '2nd Edition',
                'pages' => 178,
                'description' => 'Guide to sustainable agricultural practices for Pacific island environments.',
                'cover_image' => 'covers/agriculture.jpg',
                'pdf_file' => 'books/agriculture.pdf',
                'file_size' => 13345678,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 167,
                'download_count' => 89,
                'sort_order' => 42,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Computer Literacy for Islands',
                'subtitle' => 'Basic Technology Skills',
                'isbn' => '978-4-345678-90-1',
                'isbn13' => '978-4345678901',
                'language_id' => 1, // English
                'publisher_id' => 1, // Pacific Education Press
                'collection_id' => null,
                'publication_year' => 2022,
                'edition' => '1st Edition',
                'pages' => 145,
                'description' => 'Introduction to computer literacy and basic technology skills.',
                'cover_image' => 'covers/computer_literacy.jpg',
                'pdf_file' => 'books/computer_literacy.pdf',
                'file_size' => 10789012,
                'access_level' => 'limited',
                'is_featured' => false,
                'view_count' => 123,
                'download_count' => 45,
                'sort_order' => 43,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Plant Life',
                'subtitle' => 'Native Flora and Ethnobotany',
                'isbn' => '978-4-456789-01-2',
                'isbn13' => '978-4456789012',
                'language_id' => 1, // English
                'publisher_id' => 7, // University of Guam Press
                'collection_id' => 2, // Micronesian Science Fundamentals
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 234,
                'description' => 'Study of native Pacific island plants and their traditional uses.',
                'cover_image' => 'covers/plant_life.jpg',
                'pdf_file' => 'books/plant_life.pdf',
                'file_size' => 16567890,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 189,
                'download_count' => 89,
                'sort_order' => 44,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Community Development',
                'subtitle' => 'Building Stronger Island Communities',
                'isbn' => '978-4-567890-12-3',
                'isbn13' => '978-4567890123',
                'language_id' => 1, // English
                'publisher_id' => 9, // FSM Department of Education
                'collection_id' => null,
                'publication_year' => 2021,
                'edition' => '1st Edition',
                'pages' => 198,
                'description' => 'Guide to community development practices for Pacific island societies.',
                'cover_image' => 'covers/community_dev.jpg',
                'pdf_file' => 'books/community_dev.pdf',
                'file_size' => 14890123,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 156,
                'download_count' => 78,
                'sort_order' => 45,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Weather Patterns',
                'subtitle' => 'Understanding Island Climate',
                'isbn' => '978-4-678901-23-4',
                'isbn13' => '978-4678901234',
                'language_id' => 1, // English
                'publisher_id' => 8, // Oceanic Educational Materials
                'collection_id' => 2, // Micronesian Science Fundamentals
                'publication_year' => 2019,
                'edition' => '2nd Edition',
                'pages' => 167,
                'description' => 'Study of weather patterns and climate systems affecting Pacific islands.',
                'cover_image' => 'covers/weather_patterns.jpg',
                'pdf_file' => 'books/weather_patterns.pdf',
                'file_size' => 12678901,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 178,
                'download_count' => 89,
                'sort_order' => 46,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Early Childhood Education',
                'subtitle' => 'Culturally Responsive Pre-K Curriculum',
                'isbn' => '978-4-789012-34-5',
                'isbn13' => '978-4789012345',
                'language_id' => 1, // English
                'publisher_id' => 10, // Pacific Scholars Collective
                'collection_id' => 10, // Teacher Resource Toolkit
                'publication_year' => 2022,
                'edition' => '1st Edition',
                'pages' => 189,
                'description' => 'Early childhood education curriculum designed for Pacific island contexts.',
                'cover_image' => 'covers/early_childhood.jpg',
                'pdf_file' => 'books/early_childhood.pdf',
                'file_size' => 13789012,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 267,
                'download_count' => 134,
                'sort_order' => 47,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Philosophy',
                'subtitle' => 'Traditional Wisdom and Modern Thought',
                'isbn' => '978-4-890123-45-6',
                'isbn13' => '978-4890123456',
                'language_id' => 1, // English
                'publisher_id' => 4, // Cultural Heritage Books
                'collection_id' => null,
                'publication_year' => 2020,
                'edition' => '1st Edition',
                'pages' => 145,
                'description' => 'Exploration of traditional Pacific island philosophy and contemporary applications.',
                'cover_image' => 'covers/philosophy.jpg',
                'pdf_file' => 'books/philosophy.pdf',
                'file_size' => 11123456,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 123,
                'download_count' => 56,
                'sort_order' => 48,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Emergency Preparedness',
                'subtitle' => 'Disaster Response for Island Communities',
                'isbn' => '978-4-901234-56-7',
                'isbn13' => '978-4901234567',
                'language_id' => 1, // English
                'publisher_id' => 9, // FSM Department of Education
                'collection_id' => null,
                'publication_year' => 2021,
                'edition' => '2nd Edition',
                'pages' => 134,
                'description' => 'Guide to emergency preparedness and disaster response for Pacific islands.',
                'cover_image' => 'covers/emergency_prep.jpg',
                'pdf_file' => 'books/emergency_prep.pdf',
                'file_size' => 9456789,
                'access_level' => 'full',
                'is_featured' => false,
                'view_count' => 189,
                'download_count' => 89,
                'sort_order' => 49,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pacific Leadership',
                'subtitle' => 'Traditional and Contemporary Leadership Models',
                'isbn' => '978-5-012345-67-8',
                'isbn13' => '978-5012345678',
                'language_id' => 1, // English
                'publisher_id' => 10, // Pacific Scholars Collective
                'collection_id' => null,
                'publication_year' => 2022,
                'edition' => '1st Edition',
                'pages' => 178,
                'description' => 'Study of traditional and contemporary leadership models in Pacific island societies.',
                'cover_image' => 'covers/leadership.jpg',
                'pdf_file' => 'books/leadership.pdf',
                'file_size' => 12890123,
                'access_level' => 'full',
                'is_featured' => true,
                'view_count' => 234,
                'download_count' => 123,
                'sort_order' => 50,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('books')->insert($books);
    }
}