version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_library_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage/logs:/var/www/storage/logs
    ports:
      - "8899:8000"
      - "5173:5173"
      - "5174:5174"
    networks:
      - book_library_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=book_library
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: book_library_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: book_library
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - book_library_network

  nginx:
    image: nginx:alpine
    container_name: book_library_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - book_library_network
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: book_library_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - book_library_network
    depends_on:
      - db

volumes:
  mysql_data:

networks:
  book_library_network:
    driver: bridge